### 一、工具安装与运行

> 需要安装的软件主要有两个，一个是Python的编辑器-->`pycharm`；另一个是`anaconda`
> - pycharm简介：如果你已经用过开发Java应用的编辑器IDEA，那么你对pycharm将会很熟悉，因为pycharm和IDEA在我看来是一模一样。pycharm是应用于编写Python程序的编辑器。pycharm每次只能打开一个项目，不像eclipse一样，每次对所有项目都是可见的。pycharm很强大，首先他的界面很简洁，然后是有很强大的自动提示功能。pycharm官方企业版是付费的，但是如果用学校的邮箱到[jetbrains官网](https://www.jetbrains.com/)注册学生账号可免费使用一年。
> - anaconda简介：anaconda是一个集成工具，它里面集成了很多工具，包括jupyter notebook（我们主要要用到的工具）等；同时它还可以对Python库进行管理（在线更新，安装，下载）。
> - jupyter notebook简介：这是一个调试Python程序的工具。你每输入一行Python代码，它都会有相应的输出。同时，它还可以进行文档的编写。（现在这篇文档就是基于jupyter notebook写的）。

### 二、numpy

#### （一）简介

> numpy是一个用于处理矩阵和向量的Python库，它具备优良的性能（比原生的Python性能好）和强大的功能。
> 其官网[点这里](https://www.numpy.org/)

#### （二）导入numpy库

> 要引用numpy库很简单，只需要一个语句就行（如下所示），如果jupyter notebook或其他编辑器没有报错，那么说明导库成功。（事实上Python所有引库的方法都是这样的）

In [4]:
import numpy as np # as np 是给numpy取了一个别名，以后要用到numpy时，只需用np代替就行。

In [5]:
np.__version__ # 查看numpy的版本号

'1.14.0'

#### （三）numpy里面的数组

##### 1、Python List的特点

> Python是一门弱类型语言，不像Java一样，对数据类型有严格的要求。在Python中声明变量无需声明变量的数据类型。Python有三种复杂的数据结构。
> 分别为：list（链表），dict（字典），tuple（元组）。list和dict均是可变的，但是tuple是不可变的。
- 不像Java一样，一个数组里面必须存一样数据类型的数据，Python里面的list可以存不一样数据类型的数据。（如下所示）

In [6]:
list = [] # 此处声明了一个空的list

In [9]:
type(list) # 查看list的数据类型

list

In [7]:
list1 = [i for i in range(10)] # 此处声明了一个list，并且用生成表达式的方式为list赋了初值

In [8]:
list1 # 打印链表里面的所有元素

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
list1[0] # 访问第一个元素

0

In [12]:
list1[0] = 10 # 修改第一个元素
list1

[10, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
list1[0] = "huangting" # 此处将第一个元素修改为字符串“黄挺”，Python编辑器并没有报错。
list1

['huangting', 1, 2, 3, 4, 5, 6, 7, 8, 9]

> array是numpy里面的基本数据结构，numpy基于array提供强大的计算能力。它和原生的Python里面的list基本差不多。但是也有不同。最大的不同就是：
> 一个array里面只能存一样数据类型的数据

In [15]:
arr = np.array([i for i in range(10)]) # 用Python里面的list初始化一个array
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
type(arr) # 查看arr的数据类型

numpy.ndarray

In [17]:
arr[0] # 访问第一个元素

0

In [18]:
arr[0] = 100 # 修改第一个元素
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
arr[0] = "huangting" # 试图将第一个元素修改为字符串，编辑器报错

ValueError: invalid literal for int() with base 10: 'huangting'

##### 2、其他创建array的方法

In [22]:
arr1 = np.zeros([2, 2], dtype=int) # 创建一个2x2的矩阵，其所有元素都是0,数据类型为int
arr1

array([[0, 0],
       [0, 0]])

In [23]:
arr2 = np.ones([2, 2]) # 创建一个2x2的矩阵，其所有元素都是1（默认数据类型为float）
arr2

array([[1., 1.],
       [1., 1.]])

In [25]:
arr3 = np.full(shape = (3, 5), dtype = int, fill_value = 666) # 创建一个3x5的张量，其所有元素都是666，数据类型为int。（显示的指明了参数的名字）
arr3

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

##### 3、arange（按步长在一定范围内取值）

In [27]:
[i for i in range(0, 20, 2)] # 初始化了一个list，从0（含0）开始算，按步长2取值，直到20（不包含）

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [29]:
np.arange(0, 20, 2) # numpy类似上述原生Python的写法

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
[i for i in range(0, 1, 0.2)] #原生的Python步长不能取float

TypeError: 'float' object cannot be interpreted as an integer

In [31]:
np.arange(0, 1, 0.2) # numpy支持步长为float

array([0. , 0.2, 0.4, 0.6, 0.8])

In [32]:
np.arange(10) # 如果没有开始参数，默认从0开始

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 4、linspace（在一定范围内切割数据）

In [33]:
np.linspace(0, 20, 10) # 在区间[0,20)等距的切10下，取切割点的值。

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

##### 5、random(生成随机数的模块)

In [35]:
np.random.randint(0, 10) # 生成一个在区间[0, 10)内的随机整数

3

In [36]:
np.random.randint(0, 10, 10) # 生成10个在区间[0, 10)内的随机整数，返回一个array

array([2, 3, 1, 7, 0, 6, 4, 2, 9, 5])

In [37]:
np.random.randint(4, 8, size = (3,5)) # 生成一个3x5的矩阵，填充矩阵的数据为区间[4，8)内的随机整数

array([[6, 6, 6, 6, 5],
       [7, 5, 7, 5, 4],
       [6, 4, 6, 6, 4]])

In [38]:
np.random.random() # 生成一个在区间[0, 1)内的随机float

0.06967170705711534

In [39]:
np.random.random((3, 5)) # 生成一个矩阵，填充矩阵的值为[0,1)内的随机float

array([[0.98381743, 0.8871936 , 0.76707977, 0.68325672, 0.30285996],
       [0.50076888, 0.30969104, 0.19223995, 0.1637236 , 0.88901172],
       [0.73570152, 0.04849528, 0.02103817, 0.0922903 , 0.01526749]])

In [40]:
np.random.normal() # 生成一个随机噪声数据，数据满足标准正态分布。

-0.8814100420454638

In [41]:
np.random.normal(2, 3) # 生成一个随机噪声数据，数据满足均值为2，方差为3的正态分布

5.0412323800754795

In [42]:
np.random.normal(0, 1, (3, 5)) # 生成一个3x5的张量，里面的数据分布满足标准正态分布

array([[ 0.32259212, -0.98856064,  0.36406509,  1.74293277,  1.10064591],
       [ 0.05462595,  0.54482643, -0.99027695, -1.20694266,  0.10079881],
       [ 1.42504005, -0.00715777,  0.48648506, -0.03385851,  0.0655347 ]])

#### （四）numpy.array的基本操作

##### 1、基本属性

In [46]:
n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
n1.ndim # 获取n1的维度

2

In [47]:
n1.shape # 形状，此处为3x3的矩阵

(3, 3)

In [49]:
n1.size # 大小，也即有多少个数据,此处为9

9

##### 2、切片操作（很重要）

In [51]:
X = np.arange(15).reshape(3, 5) #生成一个3x5的矩阵（reshape操作之后会将，此处只要知道生成了一个矩阵即可）
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
X[0][0] # 取第0行，第0列的元素

0

In [53]:
X[(0, 0)] # 取第0行，第0列的元素

0

In [58]:
X[0]  # 取第0行的数据

array([0, 1, 2, 3, 4])

In [59]:
X[0:2] # 取[0,2)行的数据

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
X[:3] # 取第0行到第三行的数据（不包括3）

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
X[1:] # 取第1行到最后一行的数据

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
X[::] # 取所有行的数据

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
X[0:2, 0:2] # 取[0, 2)行，[0, 2)列的数据

array([[0, 1],
       [5, 6]])

In [65]:
X[0, 1] # 取第0行，第1列的数据

1

In [66]:
X[0:2, -1] # 取[0, 2)行，最后一列的数据

array([4, 9])

In [67]:
X[::2, ::2] # 取所有行，所有列的数据，行的步长为2， 列的步长也为2

array([[ 0,  2,  4],
       [10, 12, 14]])